---
es_version: 8.10.2
es_home: "/usr/share/elasticsearch"
es_conf_dir: "/etc/elasticsearch"
es_start_service: true
es_restart_on_change: true
es_users:
  native:
    elastic:
      password: "elastic" # Uncomment one time if you want change elastic password and Update group_vars/all api_password after 
    kibana_system:
      password: "{{ eol.cluster.kibana_password }}"
    remote_monitoring_user:
      password: "{{ eol.cluster.kibana_monitor_password }}"
  
es_api_scheme: "https"
es_api_host: "10.251.19.3"
es_api_port: 9200
es_api_uri: "{{ es_api_scheme }}://{{ es_api_host }}:{{ es_api_port }}"
es_security_api: "{{ '_security' if es_version is version('7.0.0', '>=') else '_xpack/security' }}"


eol:
  cluster:
    name: "Antoine_Cluster_Test"
    es_api_port: 9200
    es_transport_port: 9300
    
    # User
    api_username: "elastic"
    api_password: "elastic"
    kibana_username: "kibana_system"
    kibana_password: "kibanapassword"
    kibana_monitor_username: "remote_monitoring_user"
    kibana_monitor_password: "eol_Kibana_monitor"

    kibana_server_port: 5601
    kibana_encryptionKey: "adfr452dgj_sdgfg-5qaf!ffq@xD582qsqs45aE0L2ddqq95z" # Generate an encryption key
    eol_ca_cert_name: "ca.crt"
    #ssl_key_passphrase: "adfd5865Dnc!ds5547qad5f8g6g2abyctd" # Uncomment if private key is encrypted. (see README)