---
es_api_basic_auth_username: "{{ eol.cluster.api_username }}"
es_api_basic_auth_password: "{{ eol.cluster.api_password }}"
es_enable_auto_ssl_configuration: false
es_enable_http_ssl: false
es_enable_transport_ssl: true
es_ssl_upload: true
es_ssl_key: "files/certs/{{ inventory_hostname }}.key"
es_ssl_key_password: ""
es_ssl_certificate: "files/certs/{{ inventory_hostname }}.crt"
es_ssl_certificate_authority: "files/certs/ca.crt"
es_ssl_key_authority: "files/certs/ca.key"
es_ssl_certificate_path: "{{ es_conf_dir }}"
es_ssl_verification_mode: "certificate"
es_validate_certs: "yes"
es_delete_unmanaged_file: true
es_delete_unmanaged_native: true
es_action_auto_create_index: true