---
- set_fact: "es_major_version={{ es_version.split('.')[0] }}.x"
  when:
      - es_major_version is undefined
  tags:
      - always

- name: Set the defaults here otherwise they can't be overriden in the same play if the role is called twice
  set_fact:
    metricbeat_repo_name: "{{ es_major_version }}"


- name: RedHat - add MetricBeat repo
  become: yes
  template:
    src: 'metricbeat.repo'
    dest: '/etc/yum.repos.d/metricbeat-{{ es_major_version }}.repo'

- name: RedHat - Install Metricbeat
  become: yes
  yum:
    name: '{{ metricbeat_package_name }}{% if es_version is defined and es_version != ""  %}-{{ es_version }}{% endif %}'
    state: present
    update_cache: yes
  retries: 5
  delay: 10
  environment:
    KIBANA_PATH_CONF: "{{ metricbeat_conf_dir }}"

- name: Install Metricbeat | Copy certificates
  become: yes
  copy:
    src: "files/certs/{{ item }}"
    dest: /etc/metricbeat/certs/
    owner: root
    group: root
    mode: '0644'
  no_log: true
  loop:
    - "{{ inventory_hostname }}.key"
    - "{{ inventory_hostname }}.crt"
    - "{{ eol.cluster.eol_ca_cert_name }}"
    - "{{ eol.cluster.eol_ca_cert_key }}"
    
- name: Install Metricbeat | Configure application
  become: yes
  template:
    src: templates/metricbeat.j2
    dest: /etc/metricbeat/metricbeat.yml
    owner: root
    group: root
    mode: '0644'
  notify: restart metricbeat

- name: Metricbeat | Configure module elasticsearch
  become: yes
  template:
    src: templates/metricbeat_elasticsearch-xpack.j2
    dest: /etc/metricbeat/modules.d/elasticsearch-xpack.yml
    owner: root
    group: root
    mode: '0644'
  when: "'elasticsearch_nodes' in {{ group_names }}"
  notify: restart metricbeat

- name: Metricbeat | Configure module kibana
  become: yes
  template:
    src: templates/metricbeat_kibana-xpack.j2
    dest: /etc/metricbeat/modules.d/kibana-xpack.yml
    owner: root
    group: root
    mode: '0644'
  when: "'kibana_nodes' in {{ group_names }}"
  notify: restart metricbeat