---
- name: Install Metricbeat | Ensure all pre-requisites packages are installed
  become: yes
  yum:
    name: "https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-8.10.3-x86_64.rpm"
    state: present

- name: Install Metricbeat | Copy certificates
  become: yes
  copy:
    src: "files/certs/{{ item }}"
    dest: /etc/metricbeat/certs/
    owner: root
    group: root
    mode: '0644'
  loop:
    - "{{ inventory_hostname }}_privatekey.pem"
    - "{{ inventory_hostname }}.crt"
    - "{{ eol.cluster.eol_ca_cert_name }}"
    
- name: Install Metricbeat | Configure application
  become: yes
  template:
    src: templates/metricbeat.j2
    dest: /etc/metricbeat/metricbeat.yml
    owner: root
    group: root
    mode: '0644'
  notify: restart metricbeat

- name: Metricbeat | Configure module elasticsearch
  become: yes
  template:
    src: templates/metricbeat_elasticsearch-xpack.j2
    dest: /etc/metricbeat/modules.d/elasticsearch-xpack.yml
    owner: root
    group: root
    mode: '0644'
  when: "'elasticsearch_nodes' in {{ group_names }}"
  notify: restart metricbeat

- name: Metricbeat | Configure module kibana
  become: yes
  template:
    src: templates/metricbeat_kibana-xpack.j2
    dest: /etc/metricbeat/modules.d/kibana-xpack.yml
    owner: root
    group: root
    mode: '0644'
  when: "'kibana_nodes' in {{ group_names }}"
  notify: restart metricbeat