---

- name: RedHat - add logstash repo
  become: yes
  template:
    src: 'logstash.repo'
    dest: '/etc/yum.repos.d/logstash-{{ logstash_repo_name }}.repo'

- name: Install logstash | Ensure logstash packages is installed
  become: yes
  yum:
    name: logstash
    state: latest
    update_cache: yes

- name: Installing logstash | Manage certificates
  block:
    - name: Install logstash | Ensure cert folder eists
      become: yes
      file:
        path: /etc/logstash/certs
        state: directory
        owner: root
        group: root
        mode: '0755'

- name: Install logstash | Copy certificates
  become: yes
  copy:
    src: "files/certs/{{ item }}"
    dest: /etc/logstash/certs/
    owner: root
    group: root
    mode: '0644'
  no_log: true
  loop:
    - "{{ inventory_hostname }}.key"
    - "{{ inventory_hostname }}.crt"
    - "{{ eol.cluster.eol_ca_cert_name }}"
    - "{{ eol.cluster.eol_ca_cert_key }}"

- name: Install logstash | Enable and start service
  become: yes
  systemd:
    name: logstash
    state: started
    enabled: yes
